name = "SindbadTutorials"
uuid = "7150cb7e-b54a-4419-adf4-a3c5c2a90a47"
authors = ["dr-ko <skoirala@bgc-jena.mpg.de>"]
version = "0.1.0"

[deps]
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ErrorMetrics = "c324fbf6-076a-4da5-8ad2-21081a6b285c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
OmniTools = "202e6067-a2be-48c9-bc21-3d3d20912f89"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sindbad = "36c3e672-7dee-4606-99b5-7e5d8d85a313"
TimeSamplers = "a27efc82-29b7-4223-84cd-12fc64c7a5bb"

[compat]
AWSS3 = "0.11.4"
BenchmarkTools = "1.6.0"
CMAEvolutionStrategy = "0.2.6"
Dates = "1.11.0"
IJulia = "1.27.0"
Pkg = "1.11.0"
Plots = "1.40.13"
Pluto = "0.20.8"
PlutoUI = "0.7.62"
Preferences = "1.4.3"
Reexport = "1.2.2"
Revise = "3.13.2"
Sindbad = "0.1.1"
